name: pull and run on merge
'on':
  push:
    branches:
      - production
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /usr
          ls -a
        host: 95.170.206.130
        user: root
        key: ${{ secrets.AAA }}
